### ISSUE TITLE
Schema validation fails when fields are nullable

### ISSUE THREAD

**Issue by chelliwell** [sahb1239/SAHB.GraphQLClient#91]
I have a 'query' (being used for a subscription) class defined as follows:
```
    public class Posn
    {
        public decimal lat { get; set; }
        public decimal lng { get; set; }
    }
    public class Record
    {
        public UInt64 id { get; set; }
        public Posn position { get; set; }
    }
```
However the server might return null values for Posn.lat and Posn.lng - in order to still receive the responses I have to change the class definition to 
```
    public class Posn
    {
        public decimal? lat { get; set; }
        public decimal? lng { get; set; }
    }
```
But then the schema validation fails:
```
Expected is Single or Double or Decimal, actual is Nullable`1
```

**Comment by chelliwell** [comment]
Oh, I see the latest develop branch has removed the Validation stuff.... :(

**Comment by sahb1239** [comment]
It's not removed just moved here:
https://github.com/sahb1239/SAHB.GraphQLClient/tree/develop/src/SAHB.GraphQLClient/Introspection

I expect to look at the issue in the next days.

**Comment by sahb1239** [comment]
This is now fixed in 2.1.1

**Comment by chelliwell** [comment]
Hi, I think 2.1.2-beta0001 does resolve this.
However I was still getting errors e.g. "dfRdr.record.emitterIdConfidence should be nullable"
So I had to change the server schema such as 
emitterIdConfidence: Int!,
to mark it as non-nullable. [Though didn't need to for String fields]
I'd figured that the '!' was more for arguments in queries etc sent by client, rather than for the responses, but that may be my mis-understanding.

I guess I could instead define it as nullable in the client, but the aim is to get as strict-as-possible validation of everything for integration testing of client vs. server - I'll need to think about which is the most appropriate way.
But yes, this commit seems to now validate for both nullable and non-nullable, as long as the nullability also matches.

**Comment by chelliwell** [comment]
> This is now fixed in 2.1.1

Could you push the fix into the 2.2.2 branch too please?
(I'm currently using '2.2.0-simplifyhttpmeth0001', which I need for https://github.com/sahb1239/SAHB.GraphQLClient/issues/77)

Hopefully it's the same issue/fix, but I currently have a problem with nullable Floats in the schema against nullable decimal in the client class:
Expected is Single or Double or Decimal, actual is Nullable`1 
I'll see if I can temporarily switch my client to the fixed 2.1.1 to see if that fix would solve it.

**Comment by sahb1239** [comment]
It should be included in SAHB.GraphQL.Client.2.2.0-alpha0082.nupkg.

**Comment by chelliwell** [comment]
Got it - thanks!
